### ISSUE TITLE
jar: prefix stripped away by resouce.getFile() 

### ISSUE THREAD

**Issue by kevinzbaker** [ridencww/goldengine#15]
com.creativewidgetworks.goldparser.util.ResourceHelper
In method findClassesInPackage(String packageName)
resouce.getFile() strips away the "jar:" prefix.
The method getJarFile(String filePath) cannot find "jar:file:/" so it is not recognizing jar files.

In getJarFile( String filePath) replacing:
filePath = filePath.substring((filePath.indexOf("jar:file:/") + 9), filePath.indexOf('!'));
  with:
filePath = filePath.substring( filePath.indexOf("/"), filePath.indexOf('!'));
Fixed it for me.
Thanks,
Kevin

**Comment by ridencww** [comment]
Thanks, Kevin.  I am reviewing your change and writing unit tests for incorporation into the master.
