### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by amryounis** [ridencww/goldengine#27]
may I ask where to find document for the engine?

**Comment by ridencww** [comment]
There isn't any formal documentation for my Java port of Devin Cook's engine. However, you can find more information on Devin's site https://goldparser.org including his Builder tool which generates the grammar file that the engine uses to process the language files. 

There are also examples in this project that shows how to implement a simple language  (Simple2 and Simple). Loading the .cgt file into the Builder will display the grammar and allow to edit it.

The GoldBuilder and engine are over 10 years old, but still are useful tools to experiment with language construction. Hope you find it useful.

**Comment by amryounis** [comment]
thank you for your comments
